easy_admin:
    site_name: 'Bizikletak'
    design:
        form_theme:   'vertical'
        color_scheme: 'light'
        assets:
            css:
#                - '/bundles/app/stylesheets/demo.css'
            js:
                - '/bundles/app/js/maplace.min.js'

