easy_admin:
    site_name: 'Bizikletak'
    design:
        form_theme:   'vertical'
        color_scheme: 'dark'
        assets:
            css:
                - '/bundles/app/css/estiloa.css'
                - '/bundles/app/css/bootstrap-datepicker3.min.css'
            js:
                - '/bundles/app/js/maplace.min.js'
                - '/bundles/app/js/bootstrap-datepicker.min.js'
                - '/bundles/app/js/bootstrap-datepicker.eu.min.js'
                - '/bundles/app/js/datetimepickerinit.js'

