<?php

namespace FrontendBundle\Repository;

/**
 * OrnitzaileakRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrnitzaileakRepository extends \Doctrine\ORM\EntityRepository
{
}
