<?php

namespace AppBundle\Repository;

/**
 * BezeroaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BezeroaRepository extends \Doctrine\ORM\EntityRepository
{
}
