<?php

namespace AppBundle\Repository;

/**
 * BezeroZigorraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BezeroZigorraRepository extends \Doctrine\ORM\EntityRepository
{
}
