<?php

namespace AppBundle\Repository;

/**
 * BizikletaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BizikletaRepository extends \Doctrine\ORM\EntityRepository
{
}
