<?php

namespace AppBundle\Repository;

/**
 * EguraldiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EguraldiaRepository extends \Doctrine\ORM\EntityRepository
{
}
