<?php

namespace AppBundle\Repository;

/**
 * GuneakRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuneakRepository extends \Doctrine\ORM\EntityRepository
{
}
