<?php

namespace AppBundle\Repository;

/**
 * IbilbideaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IbilbideaRepository extends \Doctrine\ORM\EntityRepository
{
}
