<?php

namespace AppBundle\Repository;

/**
 * MaileguakRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaileguakRepository extends \Doctrine\ORM\EntityRepository
{

}
