<?php

namespace AppBundle\Repository;

/**
 * MatxuraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatxuraRepository extends \Doctrine\ORM\EntityRepository
{
}
