<?php

namespace AppBundle\Repository;

/**
 * ZigorraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZigorraRepository extends \Doctrine\ORM\EntityRepository
{
}
