easy_admin:
    entities:
        Bezeroa:
            class: AppBundle\Entity\Bezeroa
            label: 'Bezeroak'
            list:
                title: 'Bezeroak %%entity_label%%'
                actions:
                    - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields: ['izena','nan','bazkidea','urtekoa','ordainketa','pasaitarra','alokairua','sinatuta']


            form:
                fields:
                    - { property: 'izena', label: 'Izena', css_class: 'col-sm-12 large' }
                    - { property: 'nan', label: 'N.A.N.', css_class: 'col-sm-6 large' }
                    - { property: 'iraungitze', type: 'datetime', label: 'Iraungitze fetxa', css_class: 'col-sm-6 large', 'placeholder': 'dd/mm/yyyy' }
                    - { property: 'mugikorra', label: 'Mugikorra', css_class: 'col-sm-6 large' }
                    - { property: 'email', label: 'Email', css_class: 'col-sm-6 large' }

                    - { property: 'kopurua', type: 'number', label: 'b modalitatean alta?', css_class: 'col-sm-6 large' }
                    - { property: 'kopurua2', type: 'number', label: 'Alokairua', css_class: 'col-sm-6 large' }

                    - { property: 'bazkidea', label: 'Kirolguneko bazkidea?', css_class: 'col-sm-3' }
                    - { property: 'ordainketa', label: 'Ordainketa', css_class: 'col-sm-3' }
                    - { property: 'pasaitarra', label: 'Pasaitarra', css_class: 'col-sm-3' }
                    - { property: 'alokairua', label: 'Alokairua', css_class: 'col-sm-3' }
                    - { property: 'sinatuta', label: 'Kontratua sinatua?', css_class: 'col-sm-3' }
                    - { property: 'udallangilea', label: 'Udal Langilea?', css_class: 'col-sm-3' }
                    - { property: 'baimenberezia', label: 'Baimen berezia?', css_class: 'col-sm-3' }


                    - { property: 'oharrak', type: 'ckeditor' }
                    - { property: 'zigorrak', label: 'Zigorrak', css_class: 'col-sm-12 large' }



