easy_admin:
    entities:
        Bizikleta:
            class: AppBundle\Entity\Bizikleta
            label: 'Bizikletak'
            list:
                title: 'Bizikletak %%entity_label%%'
                actions:
                    - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - 'id'
                    - { property: 'kodea', label: 'Kodea' }
#                    - { property: 'parent', label: 'Parent category' }
#                    - 'products'
            show:
                fields:
                    - 'id'
                    - { property: 'kodea', label: 'Label', css_class: 'large' }
#                    - { property: 'parent', label: 'Parent category' }
#                    - 'products'
            form:
                fields:
                    - { property: 'kodea', label: 'Label', css_class: 'col-sm-12 large' }
#                    - { property: 'parent', type_options: { placeholder: 'Select a category...' } }
