easy_admin:
    entities:
        Guneak:
            class: AppBundle\Entity\Guneak
            label: 'Guneak'
            list:
                title: '%%entity_label%%- mantenimendua'
                actions:
                    - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields: ['id','izena', 'helbidea', 'ordutegia',  'kudeatzailea']

            show:
                fields: ['id','izena', 'helbidea', 'ordutegia', 'kudeatzailea']

            form:
                fields:
                    - { property: 'izena', label: 'Izena', css_class: 'col-sm-12 large' }
                    - { property: 'helbidea', label: 'Helbidea', css_class: 'col-sm-12 large' }
                    - latitude
                    - longitude
                    - ordutegia
                    - kudeatzailea


