easy_admin:
    entities:
        Guneak:
            class: AppBundle\Entity\Guneak
            label: 'Guneak'
            list:
                title: 'Guneak %%entity_label%%'
                actions:
                    - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields: ['id','izena', 'helbidea', 'ordutegia', 'barrutia', 'kudeatzailea']
#                    - 'id'
#                    - { property: 'izena', label: 'Kodea' }

            show:
                fields: ['id','izena', 'helbidea', 'ordutegia', 'barrutia', 'kudeatzailea']
#                fields:
#                    - 'id'
#                    - { property: 'izena', label: 'Label', css_class: 'large' }
#                    - { property: 'parent', label: 'Parent category' }
#                    - 'products'
            form:
                fields:
                    - { property: 'izena', label: 'Izena', css_class: 'col-sm-12 large' }
                    - { property: 'helbidea', label: 'Helbidea', css_class: 'col-sm-12 large' }
                    - ordutegia
                    - { property: 'barruti', label: 'Barrutia' , type_options: { placeholder: 'Aukeratu barrutia...' } }
                    - kudeatzailea


