easy_admin:
    entities:
        Ibilbidea:
            class: AppBundle\Entity\Ibilbidea
            label: 'Ibilbidea'
            list:
                title: 'Ibilbidea'
                actions:
                    - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields: ['id','izena']

            show:
                fields: ['izena']

            form:
                fields: ['izena']